<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Answer */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Answers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="answer-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'can_id',
            'bat_id',
            'column1',
            'column2',
            'column3',
            'status',
            'finished_at',
            'answer_status',
            'answer_status2',
            'overall_status',
            'answer_last_saved',
            'question_last_saved',
            'answer_last_saved2',
            'created_at',
            'updated_at',
            'q1',
            'q2',
            'q3',
            'q4',
            'q5',
            'q6',
            'q7',
            'q8',
            'q9',
            'q10',
            'q11',
            'q12',
            'q13',
            'q14',
            'q15',
            'q16',
            'q17',
            'q18',
            'q19',
            'q20',
            'q21',
            'q22',
            'q23',
            'q24',
            'q25',
            'q26',
            'q27',
            'q28',
            'q29',
            'q30',
            'q31',
            'q32',
            'q33',
            'q34',
            'q35',
            'q36',
            'q37',
            'q38',
            'q39',
            'q40',
            'q41',
            'q42',
            'q43',
            'q44',
            'q45',
            'q46',
            'q47',
            'q48',
            'q49',
            'q50',
            'q51',
            'q52',
            'q53',
            'q54',
            'q55',
            'q56',
            'q57',
            'q58',
            'q59',
            'q60',
            'q61',
            'q62',
            'q63',
            'q64',
            'q65',
            'q66',
            'q67',
            'q68',
            'q69',
            'q70',
            'q71',
            'q72',
            'q73',
            'q74',
            'q75',
            'q76',
            'q77',
            'q78',
            'q79',
            'q80',
            'q81',
            'q82',
            'q83',
            'q84',
            'q85',
            'q86',
            'q87',
            'q88',
            'q89',
            'q90',
            'q91',
            'q92',
            'q93',
            'q94',
            'q95',
            'q96',
            'q97',
            'q98',
            'q99',
            'q100',
            'q101',
            'q102',
            'q103',
            'q104',
            'q105',
            'q106',
            'q107',
            'q108',
            'q109',
            'q110',
            'q111',
            'q112',
            'q113',
            'q114',
            'q115',
            'q116',
            'q117',
            'q118',
            'q119',
            'q120',
            'biz_idea:ntext',
        ],
    ]) ?>

</div>
